/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package battleship.client;

import battleship.model.ShipType;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author brian
 */
public class PlacingShipJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlacingShipJFrame
     */
    public PlacingShipJFrame(GUIPlayer player) {
        initComponents();
        
        myMapJPanel.addMouseListener( new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int width = e.getComponent().getWidth();
                int height = e.getComponent().getHeight();
                float x = e.getX();
                float y = e.getY();
                
                ShipType ship = (ShipType) shipsAvailableList.getSelectedValue();
                
                if( ship == null )
                {
                    // tell user to select ship
                    return;
                }
                
                System.out.println("width: " + width );
                System.out.println("height: " + height );
                System.out.println("x: "+ x+ "  y: " + y );
                
                int cx = (int)(x / width * 10);
                int cy = (int)(y / height * 10);
                System.out.println("calced x: "+ cx+ "  y: " + cy );
                System.out.println("placing ship type: "+ ship );
                
                //if ( player.placeShip( ship, cx, cy, true ))
                //{
                    // remove 
                //}
                //shipsAvailableList.remove(0);
                //shipsAvailableList.repaint();
            }

            @Override
            public void mousePressed(MouseEvent e) {}
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
            @Override
            public void mouseExited(MouseEvent e) {}
            }
        );
        
        // create grid
        for(int i=0;i<100;i++)
        {
            JPanel field = new JPanel();
            field.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
            myMapJPanel.add(field);
       
        }
       
        
          ArrayList<ShipType> ships = Player.getShips();
//          for( ShipType s : ships )
//          {
            shipsAvailableList.setListData(ships.toArray());
//          }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myMapJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shipsAvailableList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myMapJPanel.setName(""); // NOI18N
        myMapJPanel.setLayout(new java.awt.GridLayout(10, 10));

        shipsAvailableList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(shipsAvailableList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(myMapJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myMapJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel myMapJPanel;
    private javax.swing.JList shipsAvailableList;
    // End of variables declaration//GEN-END:variables
}
